### ISSUE TITLE
Tooltip effect desktop only

### ISSUE THREAD

**Issue by rene-haefliger** [CodyHouse/cd-tooltip-changelog#2]
Question: I want to have the effect only after a certain breackpoint. How do I achieve this? Thanks.

**Comment by claudia-romano** [comment]
Hi there, you have two options:
1) Modify the SCSS of the component and apply the `display` property inside the md media query:
```scss
.tooltip { /* tooltip element - created using js */
  position: absolute;
  // ...

  @include breakpoint(md) {
    display: inline-block;
  }
}
```
2) Use the `data-tooltip-class` attribute to add the `display@md` class to the tooltip. 
```html
<span class="tooltip-trigger js-tooltip-trigger" title="Lorem ipsum dolor sit amet, consectetur adipisicing elit." data-tooltip-class="display@md">the stars</span>
```

More info here:
https://codyhouse.co/ds/components/info/tooltip

**Comment by rene-haefliger** [comment]
Thanks, this did the job.

```css
.tooltip { /* tooltip element - created using js */
  position: absolute;
  display: none;
  // ...

  @include breakpoint(md) {
    display: inline-block;
  }
}
```
